// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD1XHHalZcfEfpRjtG22IGWqm0HT4alSQ',
    appId: '1:597020592128:android:b4afb816351191c803f0e5',
    messagingSenderId: '597020592128',
    projectId: 'quran-9bce1',
    storageBucket: 'quran-9bce1.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WDWqbH4TsPFTEEG0TmEPbuETYXAW314',
    appId: '1:597020592128:web:2feb7033d09f91d403f0e5',
    messagingSenderId: '597020592128',
    projectId: 'quran-9bce1',
    authDomain: 'quran-9bce1.firebaseapp.com',
    storageBucket: 'quran-9bce1.appspot.com',
    measurementId: 'G-J3T3E5FL0E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxNrFqAviUiZ9DiCSfVoN1Ddo_dNVjNM0',
    appId: '1:597020592128:ios:8c80ac7cc6e1b0f703f0e5',
    messagingSenderId: '597020592128',
    projectId: 'quran-9bce1',
    storageBucket: 'quran-9bce1.appspot.com',
    iosBundleId: 'com.deksheno.quran',
  );
}
