import 'package:flutter/material.dart';
import 'package:quran/models/part.dart';
import 'package:quran/models/surah.dart';

const primaryColor = Colors.brown;
const secondaryColor = Colors.brown;

const List<String> orderTypes = [
  "طلب عام",
  "طلب صيانه",
  "طلب معاينه",
  "طلب تركيب",
];

List<Surah> surahList = [
  Surah(0, "السورة"),
  Surah(1, "1. Al-Fatiha    سورة الفاتحة"),
  Surah(2, "2. Al-Baqara    سورة البقرة"),
  Surah(50, "3. Aal-e-Imran    سورة آل عمران"),
  Surah(77, "4. An-Nisa    سورة النساء"),
  Surah(106, "5. Al-Maeda    سورة المائدة"),
  Surah(128, "6. Al-Anaam    سورة الأنعام"),
  Surah(151, "7. Al-Araf    سورة الأعراف"),
  Surah(177, "8. Al-Anfal    سورة الأنفال"),
  Surah(187, "9. At-Taubah    سورة التوبة"),
  Surah(208, "10. Yunus    سورة يونس"),
  Surah(221, "11. Hud    سورة هود"),
  Surah(235, "12. Yusuf    سورة يوسف"),
  Surah(249, "13. Ar-Rad    سورة الرعد"),
  Surah(255, "14. Ibrahim    سورة إبراهيم"),
  Surah(262, "15. Al-Hijr    سورة الحجر"),
  Surah(267, "16. An-Nahl    سورة النحل"),
  Surah(282, "17. Al-Isra    سورة الإسراء"),
  Surah(293, "18.Al-Kahf    سورة الكهف"),
  Surah(305, "19. Maryam    سورة مريم"),
  Surah(312, "20. Taha    سورة طه"),
  Surah(322, "21. Al-Anbiya    سورة الأنبياء"),
  Surah(332, "22. Al-Hajj    سورة الحج"),
  Surah(342, "23. Al-Mumenoon    سورة المؤمنون"),
  Surah(350, "24. An-Noor    سورة النور"),
  Surah(359, "25. Al-Furqan    سورة الفرقان"),
  Surah(367, "26. Ash-Shuara    سورة الشعراء"),
  Surah(377, "27. An-Naml    سورة النمل"),
  Surah(385, "28. Al-Qasas    سورة القصص"),
  Surah(396, "29. Al-Ankaboot    سورة العنكبوت"),
  Surah(404, "30. Ar-Room    سورة الروم"),
  Surah(411, "31. Luqman    سورة لقمان"),
  Surah(415, "32. As-Sajda    سورة السجدة"),
  Surah(418, "33. Al-Ahzab    سورة الأحزاب"),
  Surah(428, "34. Saba    سورة سبأ"),
  Surah(434, "35. Fatir    سورة فاطر"),
  Surah(440, "36. Ya Seen    سورة يس"),
  Surah(446, "37. As-Saaffat    سورة الصافات"),
  Surah(453, "38. Sad    سورة ص"),
  Surah(458, "39. Az-Zumar    سورة الزمر"),
  Surah(467, "40. Ghafir    سورة غافر"),
  Surah(477, "41. Fussilat    سورة فصلت"),
  Surah(483, "42. Ash-Shura    سورة الشورى"),
  Surah(489, "43. Az-Zukhruf    سورة الزخرف"),
  Surah(496, "44. Ad-Dukhan    سورة الدخان"),
  Surah(499, "45. Al-Jathiya    سورة الجاثية"),
  Surah(502, "46. Al-Ahqaf    سورة الأحقاف"),
  Surah(507, "47. Muhammad    سورة محمد"),
  Surah(511, "48. Al-Fath    سورة الفتح"),
  Surah(515, "49. Al-Hujraat    سورة الحجرات"),
  Surah(518, "50. Qaf    سورة ق"),
  Surah(520, "51. Adh-Dhariyat    سورة الذاريات"),
  Surah(523, "52. At-tur    سورة الطور"),
  Surah(526, "53. An-Najm    سورة النجم"),
  Surah(528, "54. Al-Qamar    سورة القمر"),
  Surah(531, "55. Ar-Rahman    سورة الرحمن"),
  Surah(534, "56. Al-Waqia    سورة الواقعة"),
  Surah(537, "57. Al-Hadid    سورة الحديد"),
  Surah(542, "58. Al-Mujadila    سورة المجادلة"),
  Surah(545, "59. Al-Hashr    سورة الحشر"),
  Surah(549, "60. Al-Mumtahana    سورة الممتحنة"),
  Surah(551, "61. As-Saff    سورة الصف"),
  Surah(553, "62. Al-Jumua    سورة الجمعة"),
  Surah(554, "63. Al-Munafiqoon    سورة المنافقون"),
  Surah(556, "64. At-Taghabun  سورة التغا"),
  Surah(558, "65. At-Talaq    سورة الطلاق"),
  Surah(560, "66. At-Tahrim    سورة التحريم"),
  Surah(562, "67. Al-Mulk    سورة الملك"),
  Surah(564, "68. Al-Qalam    سورة القلم"),
  Surah(566, "69. Al-Haaqqa    سورة الحاقة"),
  Surah(568, "70. Al-Maarij    سورة المعارج"),
  Surah(570, "71. Nooh    سورة نوح"),
  Surah(572, "72. Al-Jinn    سورة الجن"),
  Surah(574, "73. Al-Muzzammil    سورة المزمل"),
  Surah(575, "74. Al-Muddathir    سورة المدثر"),
  Surah(577, "75. Al-Qiyama    سورة القيامة"),
  Surah(578, "76. Al-Insan    سورة الإنسان"),
  Surah(580, "77. Al-Mursalat    سورة المرسلات"),
  Surah(582, "78. An-Naba    سورة النبأ"),
  Surah(583, "79. An-Naziat    سورة النازعات"),
  Surah(585, "80. Abasa    سورة عبس"),
  Surah(586, "81. At-Takwir    سورة التكوير"),
  Surah(587, "82. AL-Infitar    سورة الإنفطار"),
  Surah(587, "83. Al-Mutaffifin    سورة المطففين"),
  Surah(589, "84. Al-Inshiqaq    سورة الانشقاق"),
  Surah(590, "85. Al-Burooj    سورة البروج"),
  Surah(591, "86. At-Tariq    سورة الطارق"),
  Surah(591, "87. Al-Ala    سورة الأعلى"),
  Surah(592, "88. Al-Ghashiya    سورة الغاشية"),
  Surah(593, "89. Al-Fajr    سورة الفجر"),
  Surah(594, "90. Al-Balad    سورة البلد"),
  Surah(595, "91. Ash-Shams    سورة الشمس"),
  Surah(595, "92. Al-Lail    سورة الليل"),
  Surah(596, "93. Ad-Dhuha    سورة الضحى"),
  Surah(596, "94. Al-Inshirah    سورة الشرح"),
  Surah(597, "95. At-Tin    سورة التين"),
  Surah(597, "96. Al-Alaq    سورة العلق"),
  Surah(598, "97. Al-Qadr    سورة القدر"),
  Surah(598, "98. Al-Bayyina    سورة البينة"),
  Surah(599, "99. Al-Zalzala    سورة الزلزلة"),
  Surah(599, "100. Al-Adiyat    سورة العاديات"),
  Surah(600, "101. Al-Qaria    سورة القارعة"),
  Surah(600, "102. At-Takathur    سورة التكاثر"),
  Surah(601, "103. Al-Asr    سورة العصر"),
  Surah(601, "104. Al-Humaza    سورة الهمزة"),
  Surah(601, "105. Al-fil    سورة الفيل"),
  Surah(602, "106. Quraish    سورة قريش"),
  Surah(602, "107. Al-Maun    سورة الماعون"),
  Surah(602, "108. Al-Kauther    سورة الكوثر"),
  Surah(603, "109. Al-Kafiroon    سورة الكافرون"),
  Surah(603, "110. An-Nasr    سورة النصر"),
  Surah(603, "111. Al-Masadd    سورة المسد"),
  Surah(604, "112. Al-Ikhlas    سورة الإخلاص"),
  Surah(604, "113. Al-Falaq    سورة الفلق"),
  Surah(604, "114. An-Nas    سورة الناس")
];

const List<String> surah = [
  "السورة",
  "1. Al-Fatiha    سورة الفاتحة",
  "2. Al-Baqara    سورة البقرة",
  "3. Aal-e-Imran    سورة آل عمران",
  "4. An-Nisa    سورة النساء",
  "5. Al-Maeda    سورة المائدة",
  "6. Al-Anaam    سورة الأنعام",
  "7. Al-Araf    سورة الأعراف",
  "8. Al-Anfal    سورة الأنفال",
  "9. At-Taubah    سورة التوبة",
  "10. Yunus    سورة يونس",
  "11. Hud    سورة هود",
  "12. Yusuf    سورة يوسف",
  "13. Ar-Rad    سورة الرعد",
  "14. Ibrahim    سورة إبراهيم",
  "15. Al-Hijr    سورة الحجر",
  "16. An-Nahl    سورة النحل",
  "17. Al-Isra    سورة الإسراء",
  "18.Al-Kahf    سورة الكهف",
  "19. Maryam    سورة مريم",
  "20. Taha    سورة طه",
  "21. Al-Anbiya    سورة الأنبياء",
  "22. Al-Hajj    سورة الحج",
  "23. Al-Mumenoon    سورة المؤمنون",
  "24. An-Noor    سورة النور",
  "25. Al-Furqan    سورة الفرقان",
  "26. Ash-Shuara    سورة الشعراء",
  "27. An-Naml    سورة النمل",
  "28. Al-Qasas    سورة القصص",
  "29. Al-Ankaboot    سورة العنكبوت",
  "30. Ar-Room    سورة الروم",
  "31. Luqman    سورة لقمان",
  "32. As-Sajda    سورة السجدة",
  "33. Al-Ahzab    سورة الأحزاب",
  "34. Saba    سورة سبأ",
  "35. Fatir    سورة فاطر",
  "36. Ya Seen    سورة يس",
  "37. As-Saaffat    سورة الصافات",
  "38. Sad    سورة ص",
  "39. Az-Zumar    سورة الزمر",
  "40. Ghafir    سورة غافر",
  "41. Fussilat    سورة فصلت",
  "42. Ash-Shura    سورة الشورى",
  "43. Az-Zukhruf    سورة الزخرف",
  "44. Ad-Dukhan    سورة الدخان",
  "45. Al-Jathiya    سورة الجاثية",
  "46. Al-Ahqaf    سورة الأحقاف",
  "47. Muhammad    سورة محمد",
  "48. Al-Fath    سورة الفتح",
  "49. Al-Hujraat    سورة الحجرات",
  "50. Qaf    سورة ق",
  "51. Adh-Dhariyat    سورة الذاريات",
  "52. At-tur    سورة الطور",
  "53. An-Najm    سورة النجم",
  "54. Al-Qamar    سورة القمر",
  "55. Ar-Rahman    سورة الرحمن",
  "56. Al-Waqia    سورة الواقعة",
  "57. Al-Hadid    سورة الحديد",
  "58. Al-Mujadila    سورة المجادلة",
  "59. Al-Hashr    سورة الحشر",
  "60. Al-Mumtahana    سورة الممتحنة",
  "61. As-Saff    سورة الصف",
  "62. Al-Jumua    سورة الجمعة",
  "63. Al-Munafiqoon    سورة المنافقون",
  "64. At-Taghabun  سورة التغا",
  "65. At-Talaq    سورة الطلاق",
  "66. At-Tahrim    سورة التحريم",
  "67. Al-Mulk    سورة الملك",
  "68. Al-Qalam    سورة القلم",
  "69. Al-Haaqqa    سورة الحاقة",
  "70. Al-Maarij    سورة المعارج",
  "71. Nooh    سورة نوح",
  "72. Al-Jinn    سورة الجن",
  "73. Al-Muzzammil    سورة المزمل",
  "74. Al-Muddathir    سورة المدثر",
  "75. Al-Qiyama    سورة القيامة",
  "76. Al-Insan    سورة الإنسان",
  "77. Al-Mursalat    سورة المرسلات",
  "78. An-Naba    سورة النبأ",
  "79. An-Naziat    سورة النازعات",
  "80. Abasa    سورة عبس",
  "81. At-Takwir    سورة التكوير",
  "82. AL-Infitar    سورة الإنفطار",
  "83. Al-Mutaffifin    سورة المطففين",
  "84. Al-Inshiqaq    سورة الانشقاق",
  "85. Al-Burooj    سورة البروج",
  "86. At-Tariq    سورة الطارق",
  "87. Al-Ala    سورة الأعلى",
  "88. Al-Ghashiya    سورة الغاشية",
  "89. Al-Fajr    سورة الفجر",
  "90. Al-Balad    سورة البلد",
  "91. Ash-Shams    سورة الشمس",
  "92. Al-Lail    سورة الليل",
  "93. Ad-Dhuha    سورة الضحى",
  "94. Al-Inshirah    سورة الشرح",
  "95. At-Tin    سورة التين",
  "96. Al-Alaq    سورة العلق",
  "97. Al-Qadr    سورة القدر",
  "98. Al-Bayyina    سورة البينة",
  "99. Al-Zalzala    سورة الزلزلة",
  "100. Al-Adiyat    سورة العاديات",
  "101. Al-Qaria    سورة القارعة",
  "102. At-Takathur    سورة التكاثر",
  "103. Al-Asr    سورة العصر",
  "104. Al-Humaza    سورة الهمزة",
  "105. Al-fil    سورة الفيل",
  "106. Quraish    سورة قريش",
  "107. Al-Maun    سورة الماعون",
  "108. Al-Kauther    سورة الكوثر",
  "109. Al-Kafiroon    سورة الكافرون",
  "110. An-Nasr    سورة النصر",
  "111. Al-Masadd    سورة المسد",
  "112. Al-Ikhlas    سورة الإخلاص",
  "113. Al-Falaq    سورة الفلق",
  "114. An-Nas    سورة الناس"
];

const List<String> verses = [
  "السورة",
  "الفاتحه",
  "البقره",
  "ال عمران",
  "النساء",
];

const List<String> parts = [
  "الجزء",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
];

List<Part> partsList = [
  Part(0, "الجزء"),
  Part(1, "1"),
  Part(22, "2"),
  Part(42, "3"),
  Part(62, "4"),
  Part(82, "5"),
  Part(102, "6"),
  Part(121, "7"),
  Part(142, "8"),
  Part(162, "9"),
  Part(182, "10"),
  Part(201, "11"),
  Part(222, "12"),
  Part(242, "13"),
  Part(262, "14"),
  Part(282, "15"),
  Part(302, "16"),
  Part(322, "17"),
  Part(342, "18"),
  Part(362, "19"),
  Part(382, "20"),
  Part(402, "21"),
  Part(422, "22"),
  Part(442, "23"),
  Part(462, "24"),
  Part(482, "25"),
  Part(502, "26"),
  Part(522, "27"),
  Part(542, "28"),
  Part(562, "29"),
  Part(582, "30"),
];

const List<Color> states_color = [
  Colors.blue,
  Colors.purple,
  Colors.green,
  Colors.red
];
