import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:quran/modules/home/controller/quran_page_controller.dart';
import 'package:quran/utils/constants.dart';
import 'package:quran/widget/download_progress_widget.dart';

class QuranPage extends StatelessWidget {
  final int page;
  final QuranPageController _quranPageController =
      Get.put(QuranPageController());

  QuranPage({
    super.key,
    required this.page,
  });

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      // 1. Wait until the dynamic directory path is initialized by the controller
      if (_quranPageController.baseDirectoryPath.value.isEmpty) {
        return const Center(child: CircularProgressIndicator());
      }

      // 2. Use the exact dynamic path generated by the device
      final String localPath =
          "${_quranPageController.baseDirectoryPath.value}/$page.png";

      if (_quranPageController.downloadingPagesStates[page] == true) {
        return const Center(
          child: CircularProgressIndicator(),
        );
      } else {
        if (File(localPath).existsSync()) {
          return Container(
            decoration: const BoxDecoration(
              color: Colors.white,
            ),
            padding: const EdgeInsets.symmetric(vertical: 20),
            child: FittedBox(
              fit: BoxFit.cover,
              clipBehavior: Clip.hardEdge,
              child: ClipRRect(
                clipBehavior: Clip.hardEdge,
                child: Image.file(
                  File(localPath),
                  // Optional but recommended: Add a Key so Flutter knows to
                  // refresh the image widget if you ever overwrite the file.
                  key: ValueKey(localPath),
                ),
              ),
            ),
          );
        } else {
          return Container(
            padding: const EdgeInsets.only(top: 200),
            child: Column(
              children: [
                if (_quranPageController.showDownload.value == false)
                  TextButton(
                    style: ButtonStyle(
                        fixedSize: WidgetStateProperty.all(const Size(150, 50)),
                        backgroundColor: WidgetStateProperty.all(Colors.brown)),
                    onPressed: () {
                      _quranPageController.downloadPage(page);
                    },
                    child: const Text(
                      "تحميل الصفحه",
                      style: TextStyle(
                        fontSize: 20,
                        color: Colors.white,
                      ),
                    ),
                  ),
                const SizedBox(
                  height: 10,
                ),
                _quranPageController.showDownload.value
                    ? ElevatedButton.icon(
                        onPressed: () async {
                          _quranPageController.cancelDownloadAllImages();
                        },
                        label: const Text(
                          "الغاء تحميل الصفحات",
                          style: TextStyle(color: Colors.black, fontSize: 20),
                        ),
                        icon: const Icon(Icons.cancel_outlined),
                      )
                    : ElevatedButton.icon(
                        onPressed: () async {
                          _quranPageController.setDownloadVisible();
                          bool state =
                              await _quranPageController.downloadAllPages();
                          if (state == true) {
                            print("all pages downloaded");
                          } else {
                            print("failed to download all pages");
                          }
                          _quranPageController.setDownloadInVisible();
                        },
                        label: const Text(
                          "تحميل كل الصفحات",
                          style: TextStyle(color: Colors.black, fontSize: 20),
                        ),
                        icon: const Icon(Icons.download_outlined),
                      ),
                const SizedBox(
                  height: 10,
                ),
                _quranPageController.showDownload.value
                    ? DownloadProgressWidget(
                        progress: _quranPageController.progress.value,
                      )
                    : const SizedBox()
              ],
            ),
          );
        }
      }
    });
  }
}
